//v19 © 2011 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TCL=="undefined"){(function(){var ea=function(){var h=document,p=h.body,r=h.documentElement,V=eval("/*@cc_on!@*/false"),L=function(a,b){for(var c="",g=0;g<b;g++)c+=a;return c},w=L("a",50),t=(Tynt.e||"")+"ic.tynt.com",B=function(a){return a.replace(/^\s+|\s+$/g,"")},C=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},M=function(a,b,c){a=h.createElement(a);C(b,a);C(c,a.style);return a},n,D;if(window.addEventListener){n=function(a,b,c){a.addEventListener(b,c,false)};D=function(a,
b,c){a.removeEventListener(b,c,false)}}else{n=function(a,b,c){a.attachEvent("on"+b,c)};D=function(a,b,c){a.detachEvent("on"+b,c)}}var W=function(a,b){var c=location.hostname.split("."),g=2;do{var j=c.slice(c.length-g,c.length).join(".");h.cookie=a+";path=/;domain=."+j+";"+b;g++}while(h.cookie.indexOf(a)==-1&&g<=c.length);if(h.cookie.indexOf(a)==-1)h.cookie=a+";path=/;"+b},E=function(a){h.readyState=="complete"?a():n(window,"load",function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&
!V)h.readyState="complete";a()},10)})},m=function(a,b){var c=[],g=function(j,f){var d="http://"+j.replace("id="+w,"id="+Tynt.join("~"));if(d.indexOf(t+"/b/p?")>-1&&typeof Tynt.b=="string")d+="&b="+Tynt.b;var i=new Image(1,1);if(f)i.onerror=f;i.src=d};m=function(j,f){c.push([j,f])};E(function(){m=g;for(var j=0;j<c.length;j++)m(c[j][0],c[j][1]);c=null});m(a,b)},N=function(a){var b=[],c="",g;for(g in a)if(a.hasOwnProperty(g)){b.push(c,g,"=",a[g]);c="&"}return b.join("")},P=function(a){for(var b=0,c=
a.length<100?a.length:100,g=0;g<c;g++)b+=a.charCodeAt(g);a=Math.floor(Math.random()*3844);c=Math.abs((new Date).getTime()-12281184E5);return O(c,7)+O((b+a)%3844,2)},Q=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?Q(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},
O=function(a,b){var c=Q(a);return L("0",b-c.length)+c},R=B((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),X=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")){a=a[b].getAttribute("href");b=location.protocol+"//"+location.host+location.pathname;var c=h.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",
9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},S=function(a){return a.replace(/^https?:\/\//,"")},Y=function(a,b){for(var c=b+"=",g=a.split(";"),j=0;j<g.length;j++){for(var f=g[j];f.charAt(0)==" ";)f=f.substring(1,f.length);if(f.indexOf(c)==0)return f.substring(c.length,f.length)}return null},Z=function(){var a=Y(h.cookie,"tracertraffic"),b=encodeURIComponent(S(X())),c=h.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:
false;var g=t+"/b/p?id="+w+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+(new Date).getTime(),j=g+(b?"&cu="+b:""),f=j+(h.referrer?"&r="+encodeURIComponent(S(h.referrer)):"");a=f+"&t="+encodeURIComponent(R);m(a,function(){m(f,function(){m(j,function(){m(g)})})})},$=function(){var a=M("style",{type:"text/css",media:"print"}),b="#tyntPrint { background-image: url(http://"+t+"/b/h?id="+Tynt.join("~")+"&ts="+(new Date).getTime()+")}";b=h.createTextNode(b);if(a.styleSheet)a.styleSheet.cssText=b.nodeValue;else a.appendChild(b);
h.getElementsByTagName("head")[0].appendChild(a);p.insertBefore(M("div",{id:"tyntPrint"}),p.firstChild)},F=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},aa=F(),ba=F(),ca=function(){var a,b=function(){window.removeEventListener("blur",b,false);G(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",
b,false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),T=function(a){G(a.target||a.srcElement,true)},x,U=function(a){a=a.target||a.srcElement;x=a.nodeName=="IMG"?a:null},H=function(){var a=function(d){return typeof d.pageX=="number"?{x:d.pageX-(r.scrollLeft?r.scrollLeft:p.scrollLeft),y:d.pageY-(r.scrollTop?r.scrollTop:p.scrollTop)}:{x:d.clientX,y:d.clientY}},b=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=p.clientWidth||d.y>=p.clientHeight},c=function(d){d=a(d);
return d.x<=0||d.y<=0||d.x>=r.clientWidth||d.y>=r.clientHeight},g=function(d){return d.target.nodeName=="#document"},j=function(d){d=a(d);return d.x<=4||d.y<=4||d.x>=r.clientWidth-4||d.y>=r.clientHeight-4},f=function(d){f=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?g:j;f(d)};return function(d){if(x&&f(d)){G(x);x=null}return true}}(),da=function(){function a(e,k){if(q(e))m(t+"/b/o?id="+w+(k?"&i=":"&l=")+encodeURIComponent(e)+
"&ts="+(new Date).getTime())}function b(e){var k=e.target||e.srcElement;if(e.button<2)for(;k&&k!=h;){e=k.href;if(k.nodeName=="A"&&e&&location.href.split("#")[0]!=e.split("#")[0]&&!/^javascript/i.test(e)){a(e);break}k=k.parentNode}}function c(){i&&a(i,true)}function g(e){e=e.target||e.srcElement;i=e.src||e.data||"flash";n(window,"blur",c)}function j(){i=null;D(window,"blur",c)}function f(e){n(e,"mouseover",g);n(e,"mouseout",j)}function d(){i&&a(i,true)}var i,q=F();n(document,"mousedown",b);E(function(){for(var e=
h.getElementsByTagName("iframe"),k=e.length-1;k>=0;k--){var o=e[k];if(o.src)f(o);else if(o.name)try{n(frames[o.name].document,"mousedown",b)}catch(s){}}e=h.getElementsByTagName("object");for(k=e.length-1;k>=0;k--)f(e[k])});n(window,"beforeunload",d);n(window,"unload",d)},I;if(Tynt.c)I=function(){};else{Tynt.c=true;I=function(){var a=true,b,c=function(g,j){var f=w,d;d=(d=B(j))?d.split(/\s+/i).length:0;var i={id:f,wc:d,c:j,f:a?1:0,t:R};C(g,i);a=false;f=i.trace_type;delete i.trace_type;d=i.g;delete i.g;
for(var q=[],e=["id","wc","f","w","h","t","c"],k=0;k<e.length;k++){var o=e[k],s=i[o];s&&q.push([o,encodeURIComponent(s).replace(/\'/g,"%27")]);delete i[o]}for(var l in i)if(i.hasOwnProperty(l))(e=i[l])&&q.push([l,encodeURIComponent(e).replace(/\'/g,"%27")]);l=[];k=2048-(("http://"+t+"/a/t/x#?").length+(3+d.length)+5);o=q.length;var v=s=0,u=0,J,y,K,z,A=0;for(l[A]={g:d,tp:null};s<o&&l.length<35;){J=q[s][0];i=q[s][1];K=J.length+2;y=k-K-v;if(y>0){e=i.substring(u,u+y);z=e.slice(-2).indexOf("%");if(z>-1){e=
i.substring(u,u+y-2+z);v+=z+2}v+=e.length+K;u+=e.length;l[A][J]=e}else v=k;if(v>=k){l[++A]={g:d,p:A};v=0}if(u>=i.length){s++;u=0}}l[0].tp=l.length;m(t+"/b/t/"+f+"?"+N(l[0]));for(d=1;d<l.length;d++)m(t+"/b/x/"+f+"?"+N(l[d]))};/tynt=nout/.test(location.href)||da();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||p.addEventListener("copy",T,false);window.addEventListener("mousedown",U,false);window.addEventListener("dragleave",H,false);window.addEventListener("dragexit",H,false);h.addEventListener("contextmenu",
ca,false)}else{p.attachEvent("oncopy",T);h.getElementsByTagName("html")[0].attachEvent("ondragleave",H);p.attachEvent("onmousedown",U)}if(h.cookie.indexOf("tracertraffic=")!=-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)W("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");Z();E($);return function(g,j){if(!h.getElementById("tyntSS")){var f;if(j)f=typeof getSelection!="undefined"?getSelection().toString():h.selection.createRange().text;var d=g.src;d&&!f&&ba(d)&&c({g:P(d),trace_type:3,
w:g.width,h:g.height},d);if(f&&B(f).length&&g.nodeName!="TEXTAREA"&&g.nodeName!="INPUT"){d=aa(f);var i={trace_type:1};if(d)b=P(f);i.g=b;var q=Tynt.m?Tynt.m(i,f):true;d&&q&&c(i,f)}}}}}var G=I()};Tynt.TCL=function(){document.body?ea():setTimeout(Tynt.TCL,300)}})();Tynt.TCL()};
